place_name: "Place Name"
intro_message: "Welcome to Place Name!"
lead: "The Most Place of Place You've Been"
announcements:
  - "Here at Place, we are dedicated to being a place in space and time!"
  - "Just another announcement, we are doing good!"